'use client';

import { useEffect, useMemo, useRef, useState } from 'react';

type Interval = '5m' | '15m' | '1h';
type Candle = { t:number; o:number; h:number; l:number; c:number; v:number; n:number; q:number; x:boolean };
type Quantiles = { range:number[]; persistence:number[]; samples:number };
type Timeframe = { lookback:number; label:string; hourBaselines:Record<string, Quantiles> };
type StudyRow = { name:string; samples:number; mfeR:number; maeR:number; ratio:number; hit2R:number; medianOutcomeR:number };
type Baseline = { generatedAt:string; dataStart:string; dataEnd:string; symbol:string; regimeSpec:{activityHigh:number; persistenceHigh:number; labels:Record<string,string>}; timeframes:Record<Interval,Timeframe>; sessions:StudyRow[]; weekdays:StudyRow[] };
type Reading = { activity:number; persistence:number; label:string; range:number; change:number };

const intervals:Interval[] = ['5m','15m','1h'];

const empty:Baseline = { generatedAt:'',dataStart:'',dataEnd:'',symbol:'BTCUSDT',regimeSpec:{activityHigh:55,persistenceHigh:65,labels:{}},timeframes:{} as Record<Interval,Timeframe>,sessions:[],weekdays:[] };
const fmt = (n:number, digits=0) => Number.isFinite(n) ? n.toLocaleString('en-US',{maximumFractionDigits:digits}) : '—';

function istParts(date:Date) { const shifted=new Date(date.getTime()+19_800_000); return { hour:shifted.getUTCHours(), weekday:(shifted.getUTCDay()+6)%7 }; }
function keyFor(date:Date) { const {weekday,hour}=istParts(date); return `${weekday}-${hour}`; }
function percentile(value:number, quantiles:number[]) {
  const probs=[10,25,50,75,90]; const points:{x:number;p:number}[]=[];
  quantiles.forEach((x,i)=>{ if(!Number.isFinite(x))return; const last=points.at(-1); if(last?.x===x) last.p=probs[i]; else points.push({x,p:probs[i]}); });
  if(!points.length)return 50; if(value<points[0].x)return 5; if(value>points.at(-1)!.x)return 95;
  for(let i=0;i<points.length;i++){ const point=points[i]; if(value===point.x)return point.p; if(i&&value<point.x){ const left=points[i-1]; return left.p+(value-left.x)/(point.x-left.x)*(point.p-left.p); } }
  return points.at(-1)!.p;
}
function calculate(candles:Candle[], lookback:number) {
  const window=candles.slice(-(lookback+1)); if(window.length!==lookback+1)return null;
  const bars=window.slice(1), close=window.at(-1)!.c, prior=window[0].c;
  const tr=bars.reduce((sum,bar,index)=>{ const previous=window[index].c; return sum+Math.max(bar.h-bar.l,Math.abs(bar.h-previous),Math.abs(bar.l-previous)); },0);
  const absMove=bars.reduce((sum,bar,index)=>sum+Math.abs(bar.c-window[index].c),0);
  return { range:tr/Math.max(close,1)*10_000, persistence:absMove?Math.abs(close-prior)/absMove:0, change:(close-prior)/Math.max(prior,1)*100 };
}
function labelFor(activity:number, persistence:number, spec:Baseline['regimeSpec']) {
  const highA=activity>=spec.activityHigh, highP=persistence>=spec.persistenceHigh;
  if(highA&&highP)return 'TREND'; if(highA)return 'CHOP'; if(highP)return 'GRIND'; return 'DEAD';
}
function append(previous:Candle[], candle:Candle) { return [...previous.filter(x=>x.t!==candle.t),candle].sort((a,b)=>a.t-b.t).slice(-120); }

function openLog() { return new Promise<IDBDatabase>((resolve,reject)=>{ const request=indexedDB.open('btc-regime-log',1); request.onupgradeneeded=()=>request.result.createObjectStore('calls',{keyPath:'timestamp'}); request.onsuccess=()=>resolve(request.result); request.onerror=()=>reject(request.error); }); }
async function saveCall(record:Record<string,unknown>) { const db=await openLog(); await new Promise<void>((resolve,reject)=>{ const tx=db.transaction('calls','readwrite'); tx.objectStore('calls').put(record); tx.oncomplete=()=>resolve(); tx.onerror=()=>reject(tx.error); }); db.close(); }
async function postToServer(record:Record<string,unknown>) { try { await fetch('/api/regime-log',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)}); } catch { /* server logging is best-effort; IndexedDB is the primary local store */ } }
async function getAllCalls():Promise<Record<string,unknown>[]> { const db=await openLog(); const rows=await new Promise<Record<string,unknown>[]>((resolve,reject)=>{ const request=db.transaction('calls').objectStore('calls').getAll(); request.onsuccess=()=>resolve(request.result as Record<string,unknown>[]); request.onerror=()=>reject(request.error); }); db.close(); return rows; }
async function exportJSON() { const rows=await getAllCalls(); const url=URL.createObjectURL(new Blob([JSON.stringify(rows,null,2)],{type:'application/json'})); const a=document.createElement('a'); a.href=url; a.download='btc-regime-calls.json'; a.click(); URL.revokeObjectURL(url); }
async function exportCSV() { const rows=await getAllCalls(); if(!rows.length)return; const keys=Object.keys(rows[0]); const lines=[keys.join(','),...rows.map(r=>keys.map(k=>{const v=r[k];return typeof v==='string'&&v.includes(',')?`"${v}"`:String(v??'')}).join(','))]; const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'})); const a=document.createElement('a'); a.href=url; a.download='btc-regime-calls.csv'; a.click(); URL.revokeObjectURL(url); }
function downloadServerLog() { const a=document.createElement('a'); a.href='/api/regime-log'; a.download='regime-log.jsonl'; a.click(); }

export default function Home() {
  const [baseline,setBaseline]=useState<Baseline>(empty); const [candles,setCandles]=useState<Record<Interval,Candle[]>>({'5m':[],'15m':[],'1h':[]}); const [status,setStatus]=useState<'loading'|'live'|'stale'|'error'>('loading'); const [message,setMessage]=useState('Loading research baseline and closed candle history…'); const lastMessage=useRef(0); const lastLogged=useRef(0);
  const put=(interval:Interval,candle:Candle)=>setCandles(previous=>({...previous,[interval]:append(previous[interval],candle)}));
  useEffect(()=>{ fetch('/baseline.json').then(r=>r.ok?r.json():Promise.reject()).then(setBaseline).catch(()=>setMessage('Baseline JSON is missing — run the research pipeline before deploying.')); },[]);
  useEffect(()=>{ let cancelled=false; Promise.all(intervals.map(async interval=>{ const response=await fetch(`https://fapi.binance.com/fapi/v1/klines?symbol=BTCUSDT&interval=${interval}&limit=120`); if(!response.ok)throw new Error(`History request failed for ${interval}`); const now=Date.now(); const rows=await response.json(); const closed=rows.filter((row:number[])=>Number(row[6])<=now).map((row:number[])=>({t:+row[0],o:+row[1],h:+row[2],l:+row[3],c:+row[4],v:+row[5],q:+row[7],n:+row[8],x:true})); if(!cancelled)setCandles(previous=>({...previous,[interval]:closed})); })).then(()=>{if(!cancelled)setMessage('Closed historical candles loaded; waiting for Binance stream.');}).catch(()=>{if(!cancelled)setMessage('Could not seed Binance history. Check network access; no forming candle is used for scoring.');}); return()=>{cancelled=true;}; },[]);
  useEffect(()=>{ const streams=intervals.map(x=>`btcusdt@kline_${x}`).join('/'); let socket:WebSocket|undefined, retry=0, timer:ReturnType<typeof setTimeout>; const connect=()=>{ socket=new WebSocket(`wss://fstream.binance.com/stream?streams=${streams}`); socket.onopen=()=>{retry=0;lastMessage.current=Date.now();setStatus('live');setMessage('Live Binance Futures stream connected; decisions update on closed candles.');}; socket.onmessage=event=>{ const k=JSON.parse(event.data)?.data?.k; if(!k)return; lastMessage.current=Date.now(); if(k.x&&intervals.includes(k.i as Interval))put(k.i as Interval,{t:+k.t,o:+k.o,h:+k.h,l:+k.l,c:+k.c,v:+k.v,n:+k.n,q:+k.q,x:true}); }; socket.onclose=()=>{setStatus('stale');setMessage('Stream disconnected — reconnecting. Last closed-candle reading is retained.'); retry=Math.min(retry+1,6); timer=setTimeout(connect,Math.min(30_000,1_000*2**retry));}; socket.onerror=()=>socket?.close(); }; try{connect();}catch{setStatus('error');setMessage('Browser WebSocket unavailable.');} const watch=setInterval(()=>{if(lastMessage.current&&Date.now()-lastMessage.current>90_000){setStatus('stale');setMessage('No Binance message for 90 seconds — waiting for reconnect.');}},15_000); return()=>{clearTimeout(timer);clearInterval(watch);socket?.close();}; },[]);
  const readings=useMemo(()=>Object.fromEntries(intervals.map(interval=>{ const spec=baseline.timeframes[interval]; const metrics=spec?calculate(candles[interval],spec.lookback):null; if(!spec||!metrics||!candles[interval].length)return [interval,null]; const b=spec.hourBaselines[keyFor(new Date(candles[interval].at(-1)!.t))]; const activity=percentile(metrics.range,b?.range??[]), persistence=percentile(metrics.persistence,b?.persistence??[]); return [interval,{...metrics,activity,persistence,label:labelFor(activity,persistence,baseline.regimeSpec)}]; })) as Record<Interval,Reading|null>,[baseline,candles]);
  const primary=readings['5m']; const view=primary??{activity:0,persistence:0,label:'WAIT',range:0,change:0};
  useEffect(()=>{ const last=candles['5m'].at(-1); if(!last||!primary||last.t===lastLogged.current)return; lastLogged.current=last.t; const record={timestamp:last.t,at:new Date(last.t).toISOString(),label:primary.label,activity:primary.activity,persistence:primary.persistence,rangeBp:primary.range,changePct:primary.change,context15m:readings['15m']?.label??'WAIT',context1h:readings['1h']?.label??'WAIT'}; saveCall(record).catch(()=>setMessage('Live analysis works, but IndexedDB logging is unavailable in this browser.')); postToServer(record); },[candles,primary,readings]);
  const statusText=status==='live'?'LIVE':status==='stale'?'STALE':'OFFLINE'; const when=primary?new Date(candles['5m'].at(-1)!.t).toLocaleString('en-IN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'short',timeZone:'Asia/Kolkata'}):'waiting for closed history';
  const confirm15=['TREND','GRIND'].includes(readings['15m']?.label??''); const confirm1h=['TREND','GRIND'].includes(readings['1h']?.label??'');
  const decision=view.label==='TREND'?(confirm15&&confirm1h?'Momentum is aligned across 5m, 15m, and 1h. Scan only for your setup.':confirm15?'Short-term momentum is present; wait for 1h alignment before sizing up.':'Short-term momentum lacks 15m confirmation. Wait.') :view.label==='GRIND'?(confirm15?'Direction persists, but range is subdued. Lower expectations.':'Slow direction lacks 15m confirmation. Wait.') :view.label==='CHOP'?'Volatile but directionless. Avoid momentum setups.':'Wait for cleaner movement.';
  return <main className="shell"><header className="topbar"><div><div className="eyebrow">BTC / USDT perpetual · market regime</div><h1>Should you trade now?</h1><p className="sub">A closed-candle, research-backed read for 5–15 minute traders. It describes market conditions; it does not predict price.</p></div><div className="live-pill"><span className={`dot ${status!=='live'?'off':''}`}/>{statusText}</div></header>
    <section className="hero"><div className="card regime-card"><div className="kicker">Current regime · IST</div><div className={`regime ${view.label.toLowerCase()}`}>{view.label}</div><div className="decision">{decision}</div><div className="stamp">{when} · closed 5m rolling window</div></div><div className="metrics"><div className="card metric"><div className="metric-label">Activity percentile</div><div className="metric-value">{primary?`${fmt(view.activity)}th`:'—'}</div><div className="metric-note">60m range vs this IST hour × weekday</div></div><div className="card metric"><div className="metric-label">Persistence</div><div className="metric-value">{primary?`${fmt(view.persistence)}th`:'—'}</div><div className="metric-note">Net move / total absolute movement</div></div><div className="card metric"><div className="metric-label">15m context</div><div className={`metric-value ${readings['15m']?.label.toLowerCase()??''}`}>{readings['15m']?.label??'—'}</div><div className="metric-note">2h confirmation window</div></div><div className="card metric"><div className="metric-label">1h context</div><div className={`metric-value ${readings['1h']?.label.toLowerCase()??''}`}>{readings['1h']?.label??'—'}</div><div className="metric-note">6h context window</div></div></div></section>
    <section className="grid"><div className="card section"><div className="section-head"><h2 className="section-title">Why this label?</h2><span className="section-note">two-axis local percentile</span></div><div className="bars"><div className="bar-row"><span className="bar-label">ACTIVITY</span><div className="bar-track"><div className="bar-fill" style={{width:`${Math.min(100,view.activity)}%`}}/></div><span className="bar-score">{fmt(view.activity)} / 100</span></div><div className="bar-row"><span className="bar-label">PERSISTENCE</span><div className="bar-track"><div className="bar-fill" style={{width:`${Math.min(100,view.persistence)}%`}}/></div><span className="bar-score">{fmt(view.persistence)} / 100</span></div></div><div className="explain"><strong>Quadrant rule:</strong> high activity + high persistence is TREND; high activity + low persistence is CHOP; low activity + high persistence is GRIND; low + low is DEAD. Thresholds come from the same generated artifact used in research.</div><div className="explain"><strong>Calibration note:</strong> the baseline was fit on a more volatile period (Mar–Jun 2026). In calmer markets, TREND will appear less frequently. This is by design — the filter is telling you the market is objectively quieter than the historical norm ({baseline.dataStart?.slice(0,10)} → {baseline.dataEnd?.slice(0,10)}). Re-fit periodically with <code>npm run data:pipeline</code>.</div></div><div className="card section"><div className="section-head"><h2 className="section-title">Swing-entry study</h2><span className="section-note">discrete 15m entries · OOS</span></div><table className="table"><thead><tr><th>Session</th><th className="num">n</th><th className="num">Median R</th><th className="num">2R hit</th></tr></thead><tbody>{baseline.sessions.slice(0,5).map(x=><tr key={x.name}><td>{x.name}{x.samples<15?<span className="small-sample"> (small sample)</span>:null}</td><td className="num">{x.samples}</td><td className={`num ${x.medianOutcomeR>=0?'positive':'negative'}`}>{x.medianOutcomeR.toFixed(2)}</td><td className="num">{(x.hit2R*100).toFixed(0)}%</td></tr>)}</tbody></table><div style={{height:24}}/><div className="section-head"><h2 className="section-title">Weekday read</h2><span className="section-note">non-overlapping events</span></div><table className="table"><thead><tr><th>Day</th><th className="num">n</th><th className="num">Median R</th><th className="num">2R hit</th></tr></thead><tbody>{baseline.weekdays.slice(0,5).map(x=><tr key={x.name}><td>{x.name}{x.samples<15?<span className="small-sample"> (small sample)</span>:null}</td><td className="num">{x.samples}</td><td className={`num ${x.medianOutcomeR>=0?'positive':'negative'}`}>{x.medianOutcomeR.toFixed(2)} R</td><td className="num">{(x.hit2R*100).toFixed(0)}%</td></tr>)}</tbody></table><div className="table-caveat">* Buckets with n &lt; 15 have wide confidence intervals; rankings are statistical noise and not durable trade rules.</div></div></section>
    <div className="footer"><span>{message}</span><span><button className="export" onClick={()=>exportJSON().catch(()=>setMessage('Could not export the local IndexedDB log.'))}>JSON</button> · <button className="export" onClick={()=>exportCSV().catch(()=>setMessage('No log entries to export as CSV.'))}>CSV</button> · <button className="export" onClick={downloadServerLog}>Server log</button> · {baseline.dataStart?`Baseline: ${baseline.dataStart.slice(0,10)} → ${baseline.dataEnd.slice(0,10)}`:'No baseline loaded'}</span></div>
  </main>;
}
